import type { BlogPost } from "@/app/(marketing)/blog/components/types";

export interface TocHeading {
  id: string;
  title: string;
  level: 2 | 3;
}

export interface BlogPostDetail extends BlogPost {
  headings: TocHeading[];
  relatedSlugs: string[];
}

export const categories = [
  "All",
  "Agency",
  "Client Management",
  "Payments",
  "Escrow",
  "Contracts",
  "Productivity",
  "AI",
  "Guides",
] as const;

export type Category = (typeof categories)[number];

export const blogPosts: BlogPost[] = [
  {
    id: "1",
    slug: "how-ai-writes-better-proposals",
    title: "How AI Writes Better Proposals (That Clients Actually Accept)",
    excerpt: "Winning proposals aren't about writing more—they're about writing smarter. Learn how AI helps agencies and freelancers create personalized, persuasive proposals that clients are more likely to accept.",
    coverGradient: "from-violet/15 via-info/10 to-violet/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_12_12 AM.png",
    category: "AI",
    author: { name: "Janvi Singhal", initials: "JS", role: "Founder, ORKA" },
    readingTime: "8 min read",
    publishedAt: "2026-03-04",
    featured: false,
  },
  {
    id: "2",
    slug: "why-escrow-is-the-future-of-client-payments",
    title: "Why Escrow Is the Future of Client Payments",
    excerpt: "Build trust, reduce risk, and get paid on time with milestone-based escrow payments.",
    coverGradient: "from-teal/15 via-teal/8 to-lime/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_22_04 AM.png",
    category: "Payments",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "7 min read",
    publishedAt: "2026-07-23",
    featured: true,
  },
  {
    id: "3",
    slug: "freelancer-contracts-that-protect-you",
    title: "Freelancer Contracts That Protect You (And Your Clients)",
    excerpt: "Key clauses every freelancer and agency should include in 2026.",
    coverGradient: "from-orange/12 via-orange/6 to-coral/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_22_20 AM.png",
    category: "Contracts",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "5 min read",
    publishedAt: "2026-07-22",
    featured: false,
  },
  {
    id: "4",
    slug: "managing-multiple-projects-without-losing-your-mind",
    title: "Managing Multiple Projects Without Losing Your Mind",
    excerpt: "Workflows, tools, and systems that keep your projects on track.",
    coverGradient: "from-info/12 via-info/6 to-violet/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_22_35 AM.png",
    category: "Productivity",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "8 min read",
    publishedAt: "2026-07-21",
    featured: false,
  },
  {
    id: "5",
    slug: "proposal-vs-contract-vs-invoice",
    title: "Proposal vs Contract vs Invoice: What's the Difference?",
    excerpt: "A simple breakdown every service business owner should know.",
    coverGradient: "from-violet/10 via-coral/8 to-orange/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_22_49 AM.png",
    category: "Guides",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "4 min read",
    publishedAt: "2026-07-20",
    featured: false,
  },
  {
    id: "6",
    slug: "why-milestone-based-payments-build-client-trust",
    title: "Why Milestone-Based Payments Build 10x More Client Trust",
    excerpt: "Stop chasing invoices. Start approving milestones.",
    coverGradient: "from-teal/12 via-violet/8 to-teal/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_25_36 AM.png",
    category: "Payments",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "6 min read",
    publishedAt: "2026-07-19",
    featured: false,
  },
  {
    id: "7",
    slug: "from-freelancer-to-agency-owner",
    title: "From Freelancer to Agency Owner: A Complete Guide",
    excerpt: "The systems, mindset, and tools you need to make the leap.",
    coverGradient: "from-orange/10 via-lime/8 to-teal/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_25_54 AM.png",
    category: "Agency",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "9 min read",
    publishedAt: "2026-07-18",
    featured: true,
  },
  {
    id: "8",
    slug: "how-ai-helps-agencies-win-more-clients",
    title: "How AI Helps Agencies Win More Clients in Less Time",
    excerpt: "From proposal generation to client research — AI tools that actually work.",
    coverGradient: "from-violet/15 via-violet/10 to-info/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_26_09 AM.png",
    category: "AI",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "5 min read",
    publishedAt: "2026-07-17",
    featured: false,
  },
  {
    id: "9",
    slug: "7-client-management-mistakes-that-cost-agencies-thousands",
    title: "7 Client Management Mistakes That Cost Agencies Thousands Every Year",
    excerpt: "Avoid these costly mistakes to protect your agency's revenue and reputation.",
    coverGradient: "from-coral/12 via-orange/8 to-violet/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_26_24 AM.png",
    category: "Client Management",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "7 min read",
    publishedAt: "2026-07-16",
    featured: false,
  },
  {
    id: "10",
    slug: "agency-client-onboarding-checklist",
    title: "Agency Client Onboarding Checklist (Free Template Included)",
    excerpt: "A step-by-step system to onboard clients smoothly and reduce churn.",
    coverGradient: "from-lime/12 via-lime/6 to-teal/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_26_39 AM.png",
    category: "Agency",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "6 min read",
    publishedAt: "2026-07-15",
    featured: false,
  },
  {
    id: "11",
    slug: "how-to-price-agency-services-without-losing-clients",
    title: "How to Price Agency Services Without Losing Clients",
    excerpt: "Value-based, retainer, hybrid — pick the right model for your stage.",
    coverGradient: "from-lime/10 via-orange/8 to-violet/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_27_04 AM.png",
    category: "Agency",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "7 min read",
    publishedAt: "2026-07-14",
    featured: false,
  },
  {
    id: "12",
    slug: "what-is-a-client-portal",
    title: "What Is a Client Portal? Benefits for Agencies and Freelancers",
    excerpt: "Reduce back-and-forth, build trust, and look professional overnight.",
    coverGradient: "from-info/12 via-violet/8 to-teal/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_27_18 AM.png",
    category: "Client Management",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "5 min read",
    publishedAt: "2026-07-13",
    featured: false,
  },
  {
    id: "13",
    slug: "how-to-get-paid-faster-as-a-freelancer",
    title: "How to Get Paid Faster as a Freelancer",
    excerpt: "Practical strategies to speed up your payment cycle and improve cash flow.",
    coverGradient: "from-teal/15 via-info/8 to-violet/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_27_37 AM.png",
    category: "Payments",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "5 min read",
    publishedAt: "2026-07-12",
    featured: false,
  },
  {
    id: "14",
    slug: "late-payments-why-clients-delay-paying",
    title: "Late Payments: Why Clients Delay Paying (and How to Stop It)",
    excerpt: "Understand why late payments happen and how to prevent them.",
    coverGradient: "from-coral/12 via-orange/8 to-coral/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_27_51 AM.png",
    category: "Payments",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "6 min read",
    publishedAt: "2026-07-11",
    featured: false,
  },
  {
    id: "15",
    slug: "best-invoicing-practices-for-agencies",
    title: "Best Invoicing Practices for Agencies",
    excerpt: "Streamline your invoicing process to get paid faster and reduce disputes.",
    coverGradient: "from-violet/12 via-teal/8 to-violet/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_28_04 AM.png",
    category: "Payments",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "5 min read",
    publishedAt: "2026-07-10",
    featured: false,
  },
  {
    id: "16",
    slug: "milestone-payments-vs-hourly-billing",
    title: "Milestone Payments vs Hourly Billing",
    excerpt: "Which payment model works best for your agency or freelance business?",
    coverGradient: "from-teal/10 via-violet/8 to-teal/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_28_19 AM.png",
    category: "Payments",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "6 min read",
    publishedAt: "2026-07-09",
    featured: false,
  },
  {
    id: "17",
    slug: "escrow-vs-upfront-payments",
    title: "Escrow vs Upfront Payments",
    excerpt: "Understand the pros and cons of each approach for agencies and freelancers.",
    coverGradient: "from-teal/12 via-lime/8 to-teal/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_28_38 AM.png",
    category: "Escrow",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "5 min read",
    publishedAt: "2026-07-08",
    featured: false,
  },
  {
    id: "18",
    slug: "cross-border-payments-for-freelancers",
    title: "Cross-Border Payments for Freelancers",
    excerpt: "How to accept international payments without losing money to fees and delays.",
    coverGradient: "from-info/12 via-teal/8 to-info/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_28_48 AM.png",
    category: "Payments",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "6 min read",
    publishedAt: "2026-07-07",
    featured: false,
  },
  {
    id: "19",
    slug: "how-to-invoice-international-clients",
    title: "How to Invoice International Clients",
    excerpt: "A practical guide to invoicing clients across borders professionally.",
    coverGradient: "from-violet/10 via-info/8 to-violet/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_29_00 AM.png",
    category: "Payments",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "5 min read",
    publishedAt: "2026-07-06",
    featured: false,
  },
  {
    id: "20",
    slug: "best-ai-tools-for-agencies",
    title: "Best AI Tools for Agencies",
    excerpt: "Discover the AI tools that help agencies work faster, smarter, and more profitably.",
    coverGradient: "from-violet/15 via-info/10 to-violet/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_29_13 AM.png",
    category: "AI",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "7 min read",
    publishedAt: "2026-07-05",
    featured: false,
  },
  {
    id: "21",
    slug: "how-ai-saves-agencies-10-hours-every-week",
    title: "How AI Saves Agencies 10+ Hours Every Week",
    excerpt: "Practical ways AI eliminates repetitive tasks and frees up your team for high-value work.",
    coverGradient: "from-violet/12 via-info/8 to-violet/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_29_26 AM.png",
    category: "AI",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "6 min read",
    publishedAt: "2026-07-04",
    featured: false,
  },
  {
    id: "22",
    slug: "how-to-write-better-project-proposals-with-ai",
    title: "How to Write Better Project Proposals with AI",
    excerpt: "Use AI to create proposals that are clearer, faster, and more persuasive.",
    coverGradient: "from-violet/10 via-info/10 to-violet/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_30_02 AM.png",
    category: "AI",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "6 min read",
    publishedAt: "2026-07-03",
    featured: false,
  },
  {
    id: "23",
    slug: "ai-vs-manual-proposal-writing",
    title: "AI vs Manual Proposal Writing",
    excerpt: "Comparing speed, quality, and consistency between AI-assisted and manual proposal writing.",
    coverGradient: "from-violet/12 via-coral/8 to-violet/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_30_26 AM.png",
    category: "AI",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "5 min read",
    publishedAt: "2026-07-02",
    featured: false,
  },
  {
    id: "24",
    slug: "how-to-scale-an-agency-from-5-clients-to-50",
    title: "How to Scale an Agency from 5 Clients to 50",
    excerpt: "The systems and mindset shifts required to grow your agency sustainably.",
    coverGradient: "from-lime/12 via-orange/8 to-teal/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_30_41 AM.png",
    category: "Agency",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "8 min read",
    publishedAt: "2026-07-01",
    featured: false,
  },
  {
    id: "25",
    slug: "how-to-build-better-client-relationships",
    title: "How to Build Better Client Relationships",
    excerpt: "Practical strategies for creating long-lasting, profitable client partnerships.",
    coverGradient: "from-info/12 via-violet/8 to-info/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_31_32 AM.png",
    category: "Client Management",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "6 min read",
    publishedAt: "2026-06-30",
    featured: true,
  },
  {
    id: "26",
    slug: "how-to-handle-difficult-clients-professionally",
    title: "How to Handle Difficult Clients Professionally",
    excerpt: "Strategies for managing challenging client situations without losing your cool or your business.",
    coverGradient: "from-coral/12 via-orange/8 to-coral/5",
    image: "/BlogImages/ChatGPT Image Jul 25, 2026, 12_31_46 AM.png",
    category: "Client Management",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "6 min read",
    publishedAt: "2026-06-29",
    featured: false,
  },
  {
    id: "27",
    slug: "client-communication-best-practices",
    title: "Client Communication Best Practices",
    excerpt: "How to communicate with clients clearly, professionally, and efficiently.",
    coverGradient: "from-violet/10 via-info/8 to-violet/5",
    image: "",
    category: "Client Management",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "5 min read",
    publishedAt: "2026-06-28",
    featured: false,
  },
  {
    id: "28",
    slug: "how-to-reduce-scope-creep",
    title: "How to Reduce Scope Creep",
    excerpt: "Protect your margins and keep projects on track with these scope management strategies.",
    coverGradient: "from-orange/12 via-lime/8 to-orange/5",
    image: "",
    category: "Productivity",
    author: { name: "ORKA Team", initials: "OT", role: "ORKA Team" },
    readingTime: "6 min read",
    publishedAt: "2026-06-27",
    featured: false,
  },
];

const postDetails: Record<string, Omit<BlogPostDetail, keyof BlogPost>> = {};

const defaultDetail: Omit<BlogPostDetail, keyof BlogPost> = {
  headings: [
    { id: "introduction", title: "Introduction", level: 2 },
    { id: "content-coming-soon", title: "Content Coming Soon", level: 2 },
  ],
  relatedSlugs: [
    "how-ai-writes-better-proposals",
    "why-escrow-is-the-future-of-client-payments",
    "freelancer-contracts-that-protect-you",
  ],
};

export function getFeaturedPost(): BlogPost {
  return blogPosts.find((p) => p.featured) || blogPosts[0];
}

export function getPostsByCategory(category: string): BlogPost[] {
  if (category === "All") return blogPosts.filter((p) => !p.featured);
  return blogPosts.filter((p) => !p.featured && p.category === category);
}

export function getPostBySlug(slug: string): BlogPostDetail | undefined {
  const post = blogPosts.find((p) => p.slug === slug);
  if (!post) return undefined;
  const detail = postDetails[slug] || defaultDetail;
  return { ...post, ...detail };
}

export function getRelatedPosts(slug: string, limit?: number): BlogPost[] {
  const detail = postDetails[slug] || defaultDetail;
  const slugs = limit ? detail.relatedSlugs.slice(0, limit) : detail.relatedSlugs;
  return slugs
    .map((s) => blogPosts.find((p) => p.slug === s))
    .filter(Boolean) as BlogPost[];
}

export const tocHeadings: TocHeading[] = [
  { id: "introduction", title: "Introduction", level: 2 },
  { id: "content-coming-soon", title: "Content Coming Soon", level: 2 },
];

export const posts = blogPosts;
